name: Build and Push to ECR

on:
  push:
    branches:
      - main  # Run on push to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install jq
        uses: dcarbone/install-jq-action@v3.0.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2  # Change to your AWS region

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag and push to ECR
        run: |
          ECR_REPO="864899851722.dkr.ecr.eu-west-2.amazonaws.com/private/python-app"
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)

          docker build -t $ECR_REPO:$IMAGE_TAG .
          docker tag $ECR_REPO:$IMAGE_TAG $ECR_REPO:latest
          docker push $ECR_REPO:$IMAGE_TAG
          
          echo "FULL_IMAGE_NAME=$ECR_REPO:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update image version in Yaml files
        run: |
          yq eval '.spec.template.spec.containers[0].image = env(FULL_IMAGE_NAME)' -i test/python-app-deployment.yaml

      - name: Commit updated YAML
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "GitHub Actions"
          git add test/python-app-deployment.yaml
          git commit -m "Update image tag in test/python-app-deployment.yaml"
          git push https://github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  